CREATE TABLE CHECKLIST (
                           id BIGSERIAL PRIMARY KEY not null,
                           data VARCHAR(20),
                           hora VARCHAR(20),
                           saidaRetorno boolean,
                           placa VARCHAR(20),
                           motorista VARCHAR(50),
                           kmVeiculo double precision,
                           tracao boolean,
                           rodoar boolean,
                           calibragemPneus boolean,
                           estepe boolean,
                           freioDianteiro boolean,
                           freioTraseiro boolean,
                           amortecedor boolean,
                           molas boolean,
                           cambioOleo boolean,
                           direcaoOleo boolean,
                           limpezaRadiadorAgua boolean,
                           oleoMotor boolean,
                           retrovistor boolean,
                           paraBrisa boolean,
                           paraChoqueDianteiro boolean,
                           paraChoqueTraseiro boolean,
                           estofamento boolean,
                           cortinas boolean,
                           cintoDeSeguranca boolean,
                           freioDeEstacionamento boolean
);
SELECT * FROM CHECKLIST;