create table checklist
(
    id                    bigserial primary key not null,
    data_hora             timestamp             not null,
    data                  varchar(20)           not null,
    hora                  varchar(20)           not null,
    saidaretorno          varchar(7)            not null,
    placa                 varchar(20)           not null,
    motorista             varchar(50)           not null,
    kmveiculo             int                   not null
        constraint km_positivo check ( kmveiculo >= 0 ),
    tracao                varchar(4)            not null,
    rodoar                varchar(4)            not null,
    calibragempneus       varchar(4)            not null,
    estepe                varchar(4)            not null,
    freiodianteiro        varchar(4)            not null,
    freiotraseiro         varchar(4)            not null,
    amortecedor           varchar(4)            not null,
    molas                 varchar(4)            not null,
    cambiooleo            varchar(4)            not null,
    direcaooleo           varchar(4)            not null,
    limpezaradiadoragua   varchar(4)            not null,
    oleomotor             varchar(4)            not null,
    retrovisor            varchar(4)            not null,
    parabrisa             varchar(4)            not null,
    parachoquedianteiro   varchar(4)            not null,
    parachoquetraseiro    varchar(4)            not null,
    estofamento           varchar(4)            not null,
    cortinas              varchar(4)            not null,
    cintodeseguranca      varchar(4)            not null,
    freiodeestacionamento varchar(4)            not null
);